### ISSUE TITLE
Failed to save data on theme options

### ISSUE THREAD

**Issue by ghost** [TypeRocket/typerocket#4]
Hi, thank you very much for the responses on the permalink issue.

Following the updated documentation, the previous problem has been solved. But I got a flash message: "Invalid CSRF Token", when I save the data. Of course, the data is not stored. 

There is no message in the browser console. How do you solve this?

Thanks

**Comment by kevindees** [comment]
Hi, Can you post your code? Also, are you using the `tr_theme_options_page` filter hook?

[TypeRocket plugins and theme options docs](https://typerocket.com/docs/typerocket-plugins/)

Thanks,
Kevin

**Comment by kevindees** [comment]
Hi, this bug has now been fixed in patch [2.0.5](https://github.com/TypeRocket/typerocket/releases/tag/v2.0.5)

I was using the `PUT` method and only `POST` is supported by browsers in some cases. Everything should be working just fine now.

Thanks for reporting this bug,
Kevin

**Comment by ghost** [comment]
Hi, thank you for the bugfix

I use the default standard code of the library. Only `TR_FOLDER` of config.php is changed.

The _Invalid CSRF Token_ is fixed in patch 2.0.5 but Chrome alert appeared : _Your request had an error. 405 - Method Not Allowed_. 

And in the console: `GET http://acn.divren.co/typerocket_rest_api/v1/options/?_method=PUT&_tr_nonce_%5D%5Bcompany_phone%5D=&tr%5Btr_theme_options%5D%5Bgoogle_maps_api_key%5D= 405 (Method Not Allowed)`.

Thanks,
Bagus

**Comment by kevindees** [comment]
Hi, I just finished writing up a tutorial for you on theme options for when we get this working.

[Adding theme options for WordPress with TypeRocket](https://typerocket.com/theme-options-for-wordpress/)

I'm not able to duplicate this new error yet. I have the theme options working with a few configurations.  I have a few questions for you to help debug this problem.
- Who is your host?
- Nginx/Apache?
- Exact PHP version?
- Browser version?
- OS?
- Server OS?
- Desktop/Tablet/Mobile?

Thanks,
Kevin

**Comment by kevindees** [comment]
This patch is a shot in the dark but maybe it will fix the problem. If you could still send your configuration information that will help me find a more solid solution.

[2.0.7](https://github.com/TypeRocket/typerocket/releases/tag/v2.0.7)
- In some cases Nginx is not configured with `REQUEST_METHOD` and it can cause issues.

**Comment by ghost** [comment]
Thankyou very much for the response & the newest documentation :)

So, the 2.0.6 doesn't fix the alert of "_Your request had an error. 405 - Method Not Allowed._". I use the original code of TypeRocket. Only the `TR_FOLDER` changed.

Even, sometimes the error alert changed to: "_Your request had an error. 0-_".

Because the current project is a demo, i place it on shared hosting at CloudKilat:
- Apache
- PHP Version 5.4.37
- Server on x86_64-redhat-linux-gnu
- Using Chrome Version 44.0.2403.130 via desktop on Windows 10 TP

How to solve this?
Thanks Kevin

**Comment by kevindees** [comment]
Have you tried version 2.0.7? I added one more change right after I made the 2.0.6 update hoping it would fix the problem.

I'm on EST time here so I'll be out until the morning.

Let me know if 2.0.7 does the trick.

Thanks for your patience and help,
Kevin

**Comment by kevindees** [comment]
Hi, I did some more research this morning. I'm wondering if you are using a different domain for the AJAX request.

http://stackoverflow.com/questions/17333013/jquery-ajax-post-request-throws-405-method-not-allowed-on-restful-wcf

What is the domain of your front-end and backend? These need to be the same. Also, I'm wondering if the demo url has a redirect you don't know about.

Thanks,
Kevin

**Comment by kevindees** [comment]
Also, check the "Sources" tab and the http.js file `typerocket/assets/js/http.js`. Be sure the file is not cached. Look for `POST`.

![Screenshot, http.js file](https://cloud.githubusercontent.com/assets/348368/9248608/24280186-418b-11e5-832c-2a9c0bdd4222.png)

I have tested TypeRocket on Windows 10 with Chrome 44 and it is working; so we know it is not a browser bug :)

Thanks,
Kevin

**Comment by ghost** [comment]
Hi, I checked the `http.js` file and it was cached. After I cleared the cache and updated, the data saved. 2.0.7 works and I'm happy :D

Thanks a lot,
Bagus

**Comment by kevindees** [comment]
Perfect! I'm glad it is working now :) If you need any help in the future I'm always willing to help.

Also, I'm writing tutorials after work house; so if there is something you want to see or learn let me know and I'll see if you can cover it.

I hope TypeRocket helps you be good looking and do cool stuff with less code!

Thanks,
Kevin
